# Generated by Django 4.1.3 on 2022-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('track_list', models.TextField(max_length=250)),
                ('list', models.CharField(max_length=100)),
            ],
        ),
    ]
