# Generated by Django 4.1.3 on 2022-11-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_list',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeofday', models.CharField(choices=[('M', 'Morning (5am-11am)'), ('D', 'Day (11am-5pm)'), ('E', 'Evening (5pm-11pm)'), ('N', 'Night (11pm-5am)')], default='D', max_length=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.album')),
            ],
        ),
    ]
