# Generated by Django 4.1.3 on 2022-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_album_track_list_listen'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listen',
            name='timeofday',
            field=models.CharField(choices=[('M', 'Morning (5am-11am)'), ('D', 'Day (11am-5pm)'), ('E', 'Evening (5pm-11pm)'), ('N', 'Night (11pm-5am)')], default='D', max_length=1, verbose_name='Time of Day'),
        ),
    ]
