# Generated by Django 4.1.3 on 2022-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_list_alter_listen_options_alter_listen_timeofday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='list',
        ),
        migrations.AddField(
            model_name='album',
            name='lists',
            field=models.ManyToManyField(to='main_app.list'),
        ),
    ]
